<section class="callaction">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="big-cta">
          <div class="cta-text">
            <h2>Vista <span>Posts</span></h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="content">

  <div class="container">
    <div class="row box-gray">
      <div class="col-lg-2"></div>

      <div class="col-lg-8">
       <?php if (isset($this->posts) && count($this->posts)): ?>
        <h3 class="aligncenter">Últimos Posts</h3>

        <!--<?php print_r($this->posts); ?>-->

        <table class="table">
          <thead>
            <tr>
              <th>Id</th>
              <th>Título</th>
              <th>Cuerpo</th>
            </tr>
          </thead>
          <tbody>
            <?php for ($i=0; $i < count($this->posts); $i++): ?>
              <tr>
                <td><?php echo $this->posts[$i]['id']; ?></td>
                <td><?php echo $this->posts[$i]['titulo']; ?></td>
                <td><?php echo $this->posts[$i]['cuerpo']; ?></td>
                <td><a href="<?php echo BASE_URL.'post'.DS.'editar'.DS.$this->posts[$i]['id'] ?>" class="btn btn-theme btn-small" title="Editar"><i class="icon-editalt"></i> Editar</a></td>
                <td><a href="<?php echo BASE_URL.'post'.DS.'eliminar'.DS.$this->posts[$i]['id'] ?>" class="btn btn-danger btn-small" title="Eliminar"><i class="icon-deletefile"></i> Eliminar</a></td>
              </tr>
            <?php endfor; ?>
          </tbody>
        </table>
      <?php else: ?>
        <h3 class="aligncenter"><strong>No hay Posts !!</strong></h3>
      <?php endif; ?>
    </div>

    <div class="col-lg-2"></div>

  </div>

<?php if (Session::accesoViewEstricto(array('usuario'))): ?>
    <div class="row floatright">
    <a href="<?php BASE_URL; ?>/post/nuevo" class="btn btn-theme"  title="Agregar Post">
    <i class="icon-createfile"></i> Agregar Post</a>
  </div>
<?php endif ?>


</div>
</section>


